Remove transport abstraction
membraneframework/membrane_rtsp pull request #38
Opened 2024-04-25 10:20 UTC by Noarkhh

This PR removes the RTSP.Transport behavior, which was essentially only an abstraction over a TCP socket.

2024-04-26 13:45 UTC, mat-hek requested changes

2024-04-26 13:45 UTC, mat-hek commented on lib/membrane_rtsp/session/logic.ex
let's merge this file with `rtsp.ex`

2024-04-26 13:45 UTC, mat-hek commented on lib/membrane_rtsp/session/logic.ex
>      @moduledoc "Struct representing the state of RTSP session"
this should have `@moduledoc false`

2024-04-26 13:45 UTC, mat-hek commented on lib/membrane_rtsp/tcp_socket.ex
>    @moduledoc """
it should be `@moduledoc false`

2024-04-26 13:45 UTC, mat-hek commented on lib/membrane_rtsp/rtsp.ex
> +  @spec start_link(binary() | URI.t(), Keyword.t()) :: GenServer.on_start()
let's add a better typespec for options

2024-04-26 13:45 UTC, mat-hek commented on lib/membrane_rtsp/rtsp.ex
>      * options - a keyword list that shall be passed when executing request over
remote transport from the doc

2024-04-26 13:45 UTC, mat-hek commented on test/membrane_rtsp/session/session_logic_test.exs
> +      # state = %State{state | execution_options: [resolver: resolver]}
leftover

2024-04-26 13:45 UTC, mat-hek commented on test/membrane_rtsp/session/session_logic_test.exs
> +    # state = %State{state | execution_options: [resolver: resolver]}
leftover

2024-04-26 13:45 UTC, mat-hek commented on lib/membrane_rtsp/tcp_socket.ex
>    import Mockery.Macro
Probably can be removed here and from deps

2024-05-10 08:38 UTC, mat-hek commented on lib/membrane_rtsp/rtsp.ex
> +    @moduledoc "Struct representing the state of RTSP session"
Should be `@moduledoc false`. Generate the docs and make sure that all and only public API is there. I think we can also remove `Membrane.RTSP.Server.Logic` and `Membrane.RTSP.Server.Logic.State` from there

2024-05-10 08:38 UTC, mat-hek commented on lib/membrane_rtsp/tcp_socket.ex
>    import Mockery.Macro
bump @Noarkhh

2024-05-10 15:55 UTC, Noarkhh commented on lib/membrane_rtsp/tcp_socket.ex
>    import Mockery.Macro
Do you mean Mockery? It's still used in tests

2024-05-13 10:05 UTC, mat-hek commented on lib/membrane_rtsp/tcp_socket.ex
>    import Mockery.Macro
Ok, somehow I thought it's removed

2024-05-13 10:05 UTC, mat-hek approved these changes

2024-05-14 10:43 UTC, merged